### PR TITLE
WFBUILD-27

### PR DESCRIPTION
**Pull request by ASzc**

### CODE REVIEW

**Comment by ASzc** [comment]
This PR isn't quite ready yet. It causes a failure in the integration tests that I haven't been able to figure out yet.

The high-level problem seems to be that an InputStreamSource isn't being added to the ServerProvisioning config for subsystems.

**Comment by ASzc** [comment]
Found the problem. The API of commons-compress isn't identical to the JDK library with respect to trailing slashes in the entry names.

**Comment by stuartwdouglas** [comment]
Sorry, I only just noticed this. Does this also work on windows?

**Comment by jamezp** [comment]
This looks like it's out of date. I'm closing, but if this is still needed please feel free to rebase and reopen.

**Pull request closed without merging**
